### ISSUE TITLE
[BUG] type error when implementing `DataProvider`

### ISSUE THREAD

**Issue by soonoo** [refinedev/refine#4897]
### Describe the bug

I'm not sure if this is technically a bug, but I'm getting a [TS2322](https://stackoverflow.com/questions/56505560/how-to-fix-ts2322-could-be-instantiated-with-a-different-subtype-of-constraint?noredirect=1&lq=1) error when implementing DataProvider. 

```typescript
export const dataProvider: DataProvider = {
  getList: async (params: { resource: string }) => {
    return {
      data: [{ name: 'tom' }], // This seems valid but throws TS2322 error.
      total: 3,
    };
  },
}
```
<img width="581" alt="스크린샷 2023-09-02 오전 11 49 29" src="https://github.com/refinedev/refine/assets/5436405/15ef03c1-1d94-4f66-8570-d31e05e9b581">

https://github.com/refinedev/refine/blob/9d4b4b3776b4e1dd90e1719e4e5d3b624dd197f3/packages/core/src/contexts/data/IDataContext.ts#L137-L158
Can we remove the generics from the DataProvider type declaration and simply change the return type to BaseRecord?

### Steps To Reproduce

Please check `getList` method in below project:
https://stackblitz.com/edit/stackblitz-starters-pzgyse?file=src%2FdataProvider.tsx

### Expected behavior

It would be nice if the above implementation didn't throw an error.

**Comment by aliemir** [comment]
Hello 👋 Just wanted to leave a comment for anyone having this issue. 

The type definition of `DataProvider` is something like:

```ts
type DataProvider = {
  getList: <TData extends BaseRecord = BaseRecord>(params: GetListParams): Promise<GetListResponse<TData>>;
  ...
}
```

which denotes `getList` method's response can be typed according to the generic. This later used in the refine's codebase to get the proper types for the responses in queries and mutations. 

Since the exported `DataProvider` is not generic or has any ways to pass generics to the methods, there's no way to obtain and use the `TData` generic type in the implementation. After this, like @BatuhanW commented, there are two ways to make TypeScript happy, 

- using `any`
- or having the same definition in the implementation so we can use the `TData` generic type in our code. 

We already export the response types but the params are typed inline in the definition and not exported. For this case, we can create a simple utility type to get the parameters of the method:

```ts
type DpParams<TMethod extends keyof DataProvider> = Parameters<
    Required<DataProvider>[TMethod]
>[0];
```

then, we can use it in our definition as follows:

```ts
const myDataProvider: DataProvider = {
  getList: <TData extends BaseRecord = BaseRecord>(params: DpParams<"getList">): Promise<GetListResponse<TData> => {
   /* ... */
   },
   /* ... */
}
```

This wil get rid of the ugly repetition of types for the params 😅 It makes sense for us to export the params and let users use them if they need to, until then the `DpParams` utility can make things slightly easier 🤔

**Comment by alicanerdurmaz** [comment]
Hello @soonoo, we released this feature. Can you give us feedback when you try?

[Changelog: refine@4.44.1](https://github.com/refinedev/refine/blob/next/packages/core/CHANGELOG.md#4441)

You can easily update your project `npm run refine check-updates`

**Comment by soonoo** [comment]
@alicanerdurmaz  Thank you for the release.
Same code still gets error with 4.44.3:
https://stackblitz.com/edit/stackblitz-starters-pzgyse?file=src%2FdataProvider.tsx  

Can you check it out?

**Comment by alicanerdurmaz** [comment]
Hello again @soonoo,

I refactored [getList function here](https://stackblitz.com/edit/stackblitz-starters-ttjqv5?file=src%2FdataProvider.tsx,node_modules%2F%40refinedev%2Fcore%2Fdist%2Fcontexts%2Fdata%2FIDataContext.d.ts,node_modules%2F%40refinedev%2Fcore%2Fdist%2Finterfaces%2Findex.d.ts) according to @aliemir's [answer](https://github.com/refinedev/refine/issues/4897#issuecomment-1710894764)

**Comment by ubugnu** [comment]
Any progress on fixing this bug, it's very stressful for a Typescript purist to use `as any`!
